#
# Copyright (C) 2023 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#

ARG BASE_IMAGE=intel/dlstreamer:2023.0.0-ubuntu22-gpu682-dpcpp

# Realsense + GStreamer Realsense builds
FROM $BASE_IMAGE as realsense
ONBUILD RUN if [ -n "$HTTP_PROXY" ] ; then  echo "Acquire::http::Proxy \"$HTTP_PROXY\";" >  /etc/apt/apt.conf; fi
ONBUILD RUN apt-get update -y || true; DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential \
    autoconf \
    git \
    libssl-dev \
    libusb-1.0-0-dev \
    libudev-dev \
    pkg-config \
    libgtk-3-dev \
    libglfw3-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    nasm \
    cmake  \
    python3  \
    python3-pi \
    meson &&  \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ONBUILD RUN mkdir -p /rs
ONBUILD WORKDIR /rs
ONBUILD RUN git clone https://github.com/gwen2018/librealsense.git
ONBUILD WORKDIR /rs/librealsense
ONBUILD RUN git checkout stream_d436_b
ONBUILD COPY ./patch/libusb.h /rs/librealsense/src/libusb/libusb.h
     #./scripts/setup_udev_rules.sh && \
ONBUILD RUN mkdir build
ONBUILD WORKDIR /rs/librealsense/build
ONBUILD SHELL ["/bin/bash", "-o", "pipefail", "-c"]
ONBUILD RUN cmake ../ \
        -DBUILD_SHARED_LIBS=true \
        -DBUILD_WITH_JPEGTURBO=true \
        -DBUILD_PYTHON_BINDINGS:bool=true \
        -DBUILD_WITH_CUDA=false \
        -DFORCE_RSUSB_BACKEND=false \
        -DPYTHON_EXECUTABLE=/usr/bin/python3 \
        -DBUILD_GLSL_EXTENSIONS=false \
        -DBUILD_WITH_CPU_EXTENSIONS=true \
        -DBUILD_UNIT_TESTS=false \
	-DBUILD_GRAPHICAL_EXAMPLES=false \
	-DCMAKE_BUILD_TYPE=Release && \
    make -j"$(cat < /proc/cpuinfo |grep -c proc)" && \
    make install && \
    export PYTHONPATH="$PYTHONPATH":/usr/lib/python3/dist-packages/pyrealsense2 && \
    python3 -c "import pyrealsense2 as rs; print(rs)"

ONBUILD RUN mv /rs/librealsense/build/libjpeg-turbo/lib/libturbojpeg.so* /usr/local/lib

# Build gst realsense element. Use github version once pull request is accepted with bug fixes
ONBUILD WORKDIR /rs
ONBUILD RUN git clone https://github.com/brian-intel/realsense-gstreamer
ONBUILD WORKDIR /rs/realsense-gstreamer
ONBUILD RUN /usr/bin/meson . build && ninja -C build && \
    cp /rs/realsense-gstreamer/build/src/libgstrealsense_meta.so /opt/intel/dlstreamer/gstreamer/lib/ && \
    cp /rs/realsense-gstreamer/build/src/libgstrealsensesrc.so /opt/intel/dlstreamer/gstreamer/lib/gstreamer-1.0 && \
    cp /usr/local/lib/libturbojpeg.so* /opt/intel/dlstreamer/gstreamer/lib/

# Final build artifact
FROM $BASE_IMAGE as final

USER root

RUN if [ -n "$HTTP_PROXY" ] ; then  echo "Acquire::http::Proxy \"$HTTP_PROXY\";" >  /etc/apt/apt.conf; fi
RUN apt-get update -y || true; DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    python3  \
    python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt /requirements.txt
COPY ./sample-media/ /home/pipeline-server/vids
COPY ./configs/dlstreamer/extensions /home/pipeline-server/extensions
COPY ./configs/dlstreamer/models/2022 /home/pipeline-server/models 
COPY ./configs/dlstreamer/framework-pipelines /home/pipeline-server/framework-pipelines

RUN   wget https://github.com/dlstreamer/pipeline-zoo-models/raw/main/storage/yolov5s-416_INT8/yolo-v5.json; mv yolo-v5.json /home/pipeline-server/models/yolov5s/1/yolov5s.json

RUN   wget https://github.com/dlstreamer/pipeline-zoo-models/raw/main/storage/yolov5s-416_INT8/FP16-INT8/yolov5s.bin; mkdir /home/pipeline-server/models/yolov5s/1/FP32-INT8; mv yolov5s.bin /home/pipeline-server/models/yolov5s/1/FP32-INT8/yolov5s.bin

RUN   wget https://github.com/dlstreamer/pipeline-zoo-models/raw/main/storage/yolov5s-416_INT8/FP16-INT8/yolov5s.xml; mv yolov5s.xml /home/pipeline-server/models/yolov5s/1/FP32-INT8/yolov5s.xml 

RUN   wget https://github.com/dlstreamer/pipeline-zoo-models/raw/main/storage/efficientnet-b0_INT8/FP32-INT8/efficientnet-b0.bin;  mkdir -p /home/pipeline-server/models/efficientnet-b0/1/FP16-INT8; mv efficientnet-b0.bin /home/pipeline-server/models/efficientnet-b0/1/FP16-INT8/efficientnet-b0.bin

RUN wget https://github.com/dlstreamer/pipeline-zoo-models/raw/main/storage/efficientnet-b0_INT8/FP32-INT8/efficientnet-b0.xml; mv efficientnet-b0.xml /home/pipeline-server/models/efficientnet-b0/1/FP16-INT8/efficientnet-b0.xml

RUN  wget https://github.com/dlstreamer/pipeline-zoo-models/raw/main/storage/efficientnet-b0_INT8/efficientnet-b0.json; mv efficientnet-b0.json /home/pipeline-server/models/efficientnet-b0/1/efficientnet-b0.json




RUN pip3 install --upgrade pip --no-cache-dir -r /requirements.txt
WORKDIR /
